version: '3.7'

volumes:
  hlds-data: {}
  mysql-data: {}

x-anchors:
  - &logs
    logging:
      driver: json-file
      options:
        max-file: '5'
        max-size: 20m

services:
  hlds:
    image: ${IMAGE_NAME}:${IMAGE_TAG}
    environment:
      GAME:
      MAXPLAYERS:
      START_MAP:
      SERVER_NAME:
      STEAM_ADMINS:
      SERVER_PASSWORD:
      RCON_PASSWORD:
      HLSTATS_DAEMON_IP:
      HLSTATS_DAEMON_PORT:
    volumes:
      - type: volume
        source: hlds-data
        target: /opt/hlds
    ports:
      - ${PORT}:27015/udp
    restart: unless-stopped
    stdin_open: true
    tty: true
    <<: *logs

  hltv:
    image: ${IMAGE_NAME}:${IMAGE_TAG}
    environment:
      HLTV: "true"
      HLTV_SERVER:
      HLTV_PORT:
      SERVER_PASSWORD:
      SPECTATOR_PASSWORD:
    ports:
      - ${HLTV_PORT}:${HLTV_PORT}/udp
    restart: unless-stopped
    stdin_open: true
    tty: true
    <<: *logs

  mysql:
    image: mysql:5.5.62
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_USER: "hlds"
      MYSQL_PASSWORD:
      MYSQL_DATABASE: "hlds"
    restart: unless-stopped
    <<: *logs

  stats:
    image: ${IMAGE_NAME}:stats-${IMAGE_TAG}
    environment:
      DB_ADDR: "mysql"
      DB_USER: "hlds"
      DB_PASS: ${MYSQL_PASSWORD}
      DB_NAME: "hlds"
    restart: unless-stopped
    ports:
      - ${WWW_PORT}:80
    <<: *logs

  stats-daemon:
    image: ${IMAGE_NAME}:stats-daemon-${IMAGE_TAG}
    environment:
      DB_ADDR: "mysql"
      DB_USER: "hlds"
      DB_PASS: ${MYSQL_PASSWORD}
      DB_NAME: "hlds"
    restart: unless-stopped
    <<: *logs
