version: '3.7'

volumes:
  hlds-data:

x-anchors:
  - &logs
    logging:
      driver: json-file
      options:
        max-file: '5'
        max-size: 20m

services:
  hlds:
    image: ${IMAGE_NAME}:${IMAGE_TAG}
    environment:
      GAME:
      MAXPLAYERS:
      START_MAP:
      SERVER_NAME:
      STEAM_ADMINS:
      SERVER_PASSWORD:
      RCON_PASSWORD:
    volumes:
      - type: volume
        source: hlds-data
        target: /opt/hlds
    ports:
      - ${PORT}:27015/udp
    restart: unless-stopped
    stdin_open: true
    tty: true
    <<: *logs

  hltv:
    image: ${IMAGE_NAME}:${IMAGE_TAG}
    environment:
      HLTV: "true"
      HLTV_SERVER:
      HLTV_PORT:
      SERVER_PASSWORD:
      SPECTATOR_PASSWORD:
    ports:
      - ${HLTV_PORT}:${HLTV_PORT}/udp
    restart: unless-stopped
    stdin_open: true
    tty: true
    <<: *logs
